function hAx = bgAxis(position)

if ~exist('position','var') || isempty(position)
    position = [0 0 1 1];
end

hAx = axes('Position',position,...
           'XLim',    [0 1],...
           'YLim',    [0 1],...
           'Box',     'off',...
           'Visible', 'off',...
           'Units',   'normalized',...
           'Clipping','off',...
           'HitTest', 'off');
       
if nargout==0, clear hAx, end
